# Site settings
title: i2801 | Creative Technologist
description: "minimalist"
url: "https://i2801.github.io"
author:
  name: "i2801"
  email: "i28011@gmail.com"
  url: "https://i2801.github.io"

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
