# Site Settings
baseurl: ""
url : "https://i2801.github.io"

# Blog Settings
theme_settings :
  title : i2801
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/i2801.jpg
    username : i2801
    description : minimalist
    experience :
      - start : 0-0-0
        end :
        experience : i2801
    skills :
      - skill : Do Not Do Anything.
        value : 100  # Percent value

  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL
    github: i2801
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : "i2801-blog"

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
